### ISSUE TITLE
Versioneer installation errror

### ISSUE THREAD

**Issue by sbanerjee23** [NSLS-II/portable-fs#8]
@CJ-Wright 
```python
$ python setup.py install
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    version=versioneer.get_version(),
  File "/u24/Experiments/1703NSLSIIXPD/other_src/portable-fs/versioneer.py", line 1405, in get_version
    return get_versions()["version"]
  File "/u24/Experiments/1703NSLSIIXPD/other_src/portable-fs/versioneer.py", line 1380, in get_versions
    pieces = from_vcs_f(cfg.tag_prefix, root, verbose)
  File "/u24/Experiments/1703NSLSIIXPD/other_src/portable-fs/versioneer.py", line 1076, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by CJ-Wright** [comment]
This might be due to the git version running on the machine. We may need to update git.

**Comment by CJ-Wright** [comment]
Slapper git version is `1.7.0.4`  my local is `2.7.4`

**Comment by CJ-Wright** [comment]
also see https://github.com/warner/python-versioneer/issues/98
